
unused = "#79e11a"

[nightowl]
  gray1 = "#637777"
  gray2 = "#657b83"
  gray3 = "#aaaaaa"
  gray4 = "#d6deeb"
  black = "#011627"
  blue = "#7fdbca"
  cyan = "#82aaff"
  green = "#addb67"
  magenta = "#ff5874"
  orange = "#f78c6c"
  purple = "#c792ea"
  red = "#dc322f"
  white = "#eeeeee"
  yellow = "#b58900"

[dark]
  button = ["nightowl.black","nightowl.gray3"]
  button-focus = ["nightowl.black","nightowl.purple"]
  button-selected = ["nightowl.gray4","nightowl.gray3"]
  cmdline = ["nightowl.gray4","nightowl.black"]
  cmdline-button = ["nightowl.black","nightowl.purple"]
  cmdline-border = ["nightowl.gray4","nightowl.gray4"]
  copy-mode = ["nightowl.black","nightowl.yellow"]
  copy-mode-alt = ["nightowl.yellow","nightowl.black"]
  copy-mode-label = ["nightowl.gray4","nightowl.red"]
  current-capture = ["nightowl.gray4","unused"]
  dialog = ["nightowl.gray4","nightowl.black"]
  dialog-button = ["nightowl.black","nightowl.purple"]
  default = ["nightowl.gray4","nightowl.black"]
  filter-intermediate = ["nightowl.black","nightowl.orange"]
  filter-invalid = ["nightowl.black","nightowl.red"]
  filter-menu = ["nightowl.gray4","nightowl.black"]
  filter-valid = ["nightowl.black","nightowl.green"]
  hex-byte-selected = ["nightowl.black","nightowl.purple"]
  hex-byte-unselected = ["nightowl.gray4","nightowl.black"]
  hex-field-selected = ["nightowl.black","nightowl.cyan"]
  hex-field-unselected = ["nightowl.black","nightowl.gray4"]
  hex-interval-selected = ["nightowl.gray4","nightowl.gray2"]
  hex-interval-unselected = ["nightowl.gray4","nightowl.gray1"]
  hex-layer-selected = ["nightowl.gray4","nightowl.gray2"]
  hex-layer-unselected = ["nightowl.gray4","nightowl.gray1"]
  packet-list-cell-focus = ["nightowl.black","nightowl.purple"]
  packet-list-cell-selected = ["nightowl.gray4","nightowl.gray2"]
  packet-list-row-focus = ["nightowl.black","nightowl.cyan"]
  packet-list-row-selected = ["nightowl.gray4","nightowl.gray1"]
  packet-struct-focus = ["nightowl.black","nightowl.cyan"]
  packet-struct-selected = ["nightowl.black","nightowl.gray2"]
  progress-complete = ["nightowl.black","nightowl.purple"]
  progress-default = ["nightowl.gray4","nightowl.black"]
  progress-spinner = ["nightowl.black","nightowl.purple"]
  spinner = ["nightowl.grey2","nightowl.black"]
  stream-client = ["nightowl.gray4","nightowl.red"]
  stream-match = ["nightowl.black","nightowl.yellow"]
  stream-search = ["nightowl.black","nightowl.gray4"]
  stream-server = ["nightowl.gray4","nightowl.blue"]
  title = ["nightowl.gray4","unused"]

[light]
  button = ["nightowl.black","nightowl.gray4"]
  button-focus = ["nightowl.gray4","nightowl.purple"]
  button-selected = ["nightowl.black","nightowl.gray3"]
  cmdline = ["nightowl.black","nightowl.yellow"]
  cmdline-button = ["nightowl.yellow","nightowl.black"]
  cmdline-border = ["nightowl.black","nightowl.yellow"]
  copy-mode = ["nightowl.gray4","nightowl.yellow"]
  copy-mode-alt = ["nightowl.yellow","nightowl.gray4"]
  copy-mode-label = ["nightowl.black","nightowl.red"]
  current-capture = ["nightowl.black","unused"]
  dialog = ["nightowl.black","nightowl.yellow"]
  dialog-button = ["nightowl.yellow","nightowl.black"]
  default = ["nightowl.black","nightowl.gray4"]
  filter-intermediate = ["nightowl.black","nightowl.orange"]
  filter-invalid = ["nightowl.black","nightowl.red"]
  filter-menu = ["nightowl.black","nightowl.gray4"]
  filter-valid = ["nightowl.black","nightowl.green"]
  hex-byte-selected = ["nightowl.gray4","nightowl.purple"]
  hex-byte-unselected = ["nightowl.black","nightowl.gray4"]
  hex-field-selected = ["nightowl.black","nightowl.cyan"]
  hex-field-unselected = ["nightowl.black","nightowl.gray2"]
  hex-interval-selected = ["nightowl.gray4","nightowl.gray2"]
  hex-interval-unselected = ["nightowl.black","nightowl.gray4"]
  hex-layer-selected = ["nightowl.gray4","nightowl.gray2"]
  hex-layer-unselected = ["nightowl.black","nightowl.gray4"]
  packet-list-cell-focus = ["nightowl.gray4","nightowl.purple"]
  packet-list-cell-selected = ["nightowl.black","nightowl.gray3"]
  packet-list-row-focus = ["nightowl.gray4","nightowl.cyan"]
  packet-list-row-selected = ["nightowl.black","nightowl.gray4"]
  packet-struct-focus = ["nightowl.black","nightowl.cyan"]
  packet-struct-selected = ["nightowl.black","nightowl.gray4"]
  progress-complete = ["nightowl.gray4","nightowl.purple"]
  progress-default = ["nightowl.gray4","nightowl.black"]
  progress-spinner = ["nightowl.yellow","nightowl.black"]
  spinner = ["nightowl.yellow","nightowl.gray4"]
  stream-client = ["nightowl.gray4","nightowl.red"]
  stream-match = ["nightowl.gray4","nightowl.yellow"]
  stream-search = ["nightowl.gray4","nightowl.black"]
  stream-server = ["nightowl.gray4","nightowl.blue"]
  title = ["nightowl.gray4","unused"]